// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-C_BrI7kekR6Rw7cplHAvXR4vPtp8a8',
    appId: '1:484098097286:web:18c1ddf833f41a5bc11107',
    messagingSenderId: '484098097286',
    projectId: 'robert-flutter-iti',
    authDomain: 'robert-flutter-iti.firebaseapp.com',
    storageBucket: 'robert-flutter-iti.firebasestorage.app',
    measurementId: 'G-YSR4EZDL5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZ3WU1WfryoSEzgHJ6QSPrjr_ojeDFhY',
    appId: '1:484098097286:android:30f38caedb697613c11107',
    messagingSenderId: '484098097286',
    projectId: 'robert-flutter-iti',
    storageBucket: 'robert-flutter-iti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn237QWNxiM8ip-m-gzGsIp97J5ZeFbec',
    appId: '1:484098097286:ios:164872973690af15c11107',
    messagingSenderId: '484098097286',
    projectId: 'robert-flutter-iti',
    storageBucket: 'robert-flutter-iti.firebasestorage.app',
    iosBundleId: 'com.example.flutterItiMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn237QWNxiM8ip-m-gzGsIp97J5ZeFbec',
    appId: '1:484098097286:ios:164872973690af15c11107',
    messagingSenderId: '484098097286',
    projectId: 'robert-flutter-iti',
    storageBucket: 'robert-flutter-iti.firebasestorage.app',
    iosBundleId: 'com.example.flutterItiMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ-C_BrI7kekR6Rw7cplHAvXR4vPtp8a8',
    appId: '1:484098097286:web:4d4da28e76f40afcc11107',
    messagingSenderId: '484098097286',
    projectId: 'robert-flutter-iti',
    authDomain: 'robert-flutter-iti.firebaseapp.com',
    storageBucket: 'robert-flutter-iti.firebasestorage.app',
    measurementId: 'G-Q6LCGDHNHZ',
  );
}
